name: Auto clean fix branches

on:
  pull_request:
    types:
      - closed
    branches:
      - main

permissions:
  contents: write

jobs:
  clean:
    if: "github.event.pull_request.merged == true && startsWith(github.head_ref, 'fix/')"
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: Input check
        run: |
          echo "git push -d $GITHUB_BRANCH"
          git push origin -d "$GITHUB_BRANCH"
        env:
          GITHUB_BRANCH: ${{ github.head_ref }}