# This is a basic workflow to help you get started with Actions

name: Autoclean fix

on:
  pull_request:
    types:
      - closed
    branches:
      - main

jobs:
  clean:
    if: github.event.pull_request.merged == true
    name: Input check
    uses: dawidd6/action-delete-branch@v3
    with:
      github_token: ${{github.token}}
      branches: ${{ github.head_ref }}
#
#    runs-on: ubuntu-latest
#    steps:
#      - name: test
#        run: |
#          echo "$GITHUB_HEAD_REF"
#        env:
#          GITHUB_HEAD_REF: ${{ github.head_ref }}
